### ISSUE TITLE
Font display issues in inventory

### ISSUE THREAD

**Issue by ayanokato** [omnit3a/Nocturne-Island#17]
The font messes up in the inventory
![image](https://github.com/omnit3a/Nocturne-Island/assets/116850347/9ec5071a-5b0d-44a8-a330-baa33b40391f)

Happens with or without compiling with `-O2` and with the prebuilt binary.

A similar issue happens in the workbench, with glitching font display at the bottom of the list when compiled with the `-O2` flag

**Comment by omnit3a** [comment]
A fix will be coming out with alpha 0.3.7
